"""
Shared Alert Model
Produced by the Fusion Agent, persisted by the API Gateway,
and displayed on the React dashboard.
"""
from typing import Optional
from pydantic import BaseModel


SEVERITY_LEVELS = ("green", "yellow", "orange", "red")


class Alert(BaseModel):
    """
    A behavioural alert generated by the Fusion Agent.
    Severity levels: green (positive), yellow (mild concern),
    orange (moderate concern), red (high concern).
    """
    session_id: str
    speaker_id: str = "unknown"
    alert_type: str = ""                # Maps to a fusion signal_type
    severity: str = "yellow"           # green | yellow | orange | red
    title: str = ""
    description: str = ""
    evidence: Optional[dict] = None    # Fusion signal metadata supporting the alert
    timestamp_ms: Optional[int] = None  # When in the session the alert occurred
